image:
  repository: your-dockerhub-user/nodejs-app
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

route:
  enabled: true

persistence:
  enabled: true
  size: 5Gi
