apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "nodejs-app.name" . }}-role-6479
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]
