apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nodejs-app.name" . }}-rb-6479
subjects:
  - kind: ServiceAccount
    name: {{ include "nodejs-app.name" . }}-sa-6479
roleRef:
  kind: Role
  name: {{ include "nodejs-app.name" . }}-role-6479
  apiGroup: rbac.authorization.k8s.io
