{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "nodejs-app.name" . }}
spec:
  to:
    kind: Service
    name: {{ include "nodejs-app.name" . }}
  port:
    targetPort: 8080
  tls:
    termination: edge
{{- end }}
